title: "UD. Sinar Alam"
description: "Jual Marmer, Granit, dan Batu Alam"
intro-image: 'assets/images/intro.jpg'
email: "sinar4lam@yahoo.co.id"
timezone: "Asia/Jakarta"
url: http://sinaralam.rf.gd
baseurl:
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: "UD. Sinar Alam"
paginate: 5
disqus: ''
locale: id_ID
lang: id_ID
feed_items: 10
feed_update_period: monthly
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
show_author: false
authors:
  sinaralam:
    name: "UD. Sinar Alam"
    display_name: "Sinar Alam"
    avatar: 'assets/images/sal.png'
    email: sinar4lam@yahoo.co.id
    web:
    twitter:
    description: "Jual Marmer, Granit, dan Batu Alam"

# Social
social:
  whatsapp: +628123918051
  email: sinar4lam@yahoo.co.id

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Gems
gems: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
